[phases.setup]
nixPkgs = ["python312", "postgresql", "wkhtmltopdf", "gcc", "pkg-config"]

[phases.build]
cmds = [
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "gunicorn setup.wsgi:application --bind 0.0.0.0:$PORT"