# Generated by Django 5.2 on 2025-05-09 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Insira apenas os 8 dígitos do CEP', regex='[\\d]{8}')], verbose_name='CEP')),
                ('uf', models.CharField(max_length=2, verbose_name='Sigla (UF)')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
            ],
        ),
    ]
