# Generated by Django 5.2 on 2025-05-12 05:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Cidade')),
            ],
            options={
                'db_table': 'cidades',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=2, unique=True, verbose_name='Sigla do Estado')),
            ],
            options={
                'db_table': 'estados',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Insira apenas os 8 dígitos do CEP', regex='[\\d]{8}')], verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('irradiancia', models.FloatField(verbose_name='Índice de Irradiância (KW/m²/y)')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.cidade')),
            ],
            options={
                'db_table': 'enderecos',
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.estado'),
        ),
    ]
