# Generated by Django 5.2 on 2025-05-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='irradiancia',
            field=models.FloatField(verbose_name='Índice de Irradiância (kWh/m²/mês)'),
        ),
    ]
