# Generated by Django 5.2 on 2025-05-16 23:38

import django.db.models.deletion
import simulador.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0002_alter_endereco_irradiancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concessionaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Concessionária')),
                ('tarifa', models.FloatField(validators=[simulador.validators.validar_positivo], verbose_name='Valor da Tarifa (R$)')),
            ],
            options={
                'db_table': 'concessionarias',
            },
        ),
        migrations.CreateModel(
            name='PainelSolar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nome do Painel')),
                ('valor', models.FloatField(validators=[simulador.validators.validar_positivo], verbose_name='Valor (R$)')),
                ('potencia', models.IntegerField(validators=[simulador.validators.validar_positivo], verbose_name='Potência (W)')),
                ('altura', models.FloatField(validators=[simulador.validators.validar_positivo], verbose_name='Altura (m)')),
                ('largura', models.FloatField(validators=[simulador.validators.validar_positivo], verbose_name='Largura (m)')),
                ('area', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Área (m²)')),
            ],
            options={
                'db_table': 'paineis_solares',
            },
        ),
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0179f5d1-54b3-480e-a825-657e34400962'), primary_key=True, serialize=False, unique=True)),
                ('consumo_atual', models.IntegerField(validators=[simulador.validators.validar_positivo], verbose_name='Consumo Médio Atual (kWh)')),
                ('quantidade_paineis', models.IntegerField(validators=[simulador.validators.validar_positivo], verbose_name='Quantidade Necessária de Painéis')),
                ('area_total', models.FloatField(validators=[simulador.validators.validar_positivo], verbose_name='Área Total (m²)')),
                ('consumo_estimado', models.IntegerField(validators=[simulador.validators.validar_positivo], verbose_name='Consumo Estimado (kWh)')),
                ('total_investimento', models.FloatField(validators=[simulador.validators.validar_positivo], verbose_name='Total do Investimento (R$)')),
                ('tempo_payback', models.FloatField(validators=[simulador.validators.validar_positivo], verbose_name='Tempo de Payback (Meses)')),
                ('custo_beneficio', models.FloatField(verbose_name='Custo-benefício')),
                ('concessionaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulador.concessionaria')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulador.endereco')),
                ('painel_solar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulador.painelsolar')),
            ],
            options={
                'db_table': 'simulacoes',
            },
        ),
    ]
