# Generated by Django 5.2 on 2025-05-16 23:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0003_concessionaria_painelsolar_simulacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f2968882-ea90-4663-8a55-18fe50ecfd45'), primary_key=True, serialize=False, unique=True),
        ),
    ]
