# Generated by Django 5.2 on 2025-05-21 00:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0004_alter_simulacao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
