# Generated by Django 5.2 on 2025-05-24 16:49

import datetime
import simulador.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0005_alter_endereco_logradouro_alter_simulacao_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painelsolar',
            name='area',
        ),
        migrations.RemoveField(
            model_name='simulacao',
            name='area_total',
        ),
        migrations.RemoveField(
            model_name='simulacao',
            name='consumo_atual',
        ),
        migrations.RemoveField(
            model_name='simulacao',
            name='consumo_estimado',
        ),
        migrations.RemoveField(
            model_name='simulacao',
            name='custo_beneficio',
        ),
        migrations.RemoveField(
            model_name='simulacao',
            name='quantidade_paineis',
        ),
        migrations.RemoveField(
            model_name='simulacao',
            name='tempo_payback',
        ),
        migrations.RemoveField(
            model_name='simulacao',
            name='total_investimento',
        ),
        migrations.AddField(
            model_name='painelsolar',
            name='data_consulta',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Data de Consulta'),
        ),
        migrations.AddField(
            model_name='painelsolar',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link de Referência'),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='area_disponivel',
            field=models.FloatField(blank=True, default=40.0, null=True, validators=[simulador.validators.validar_positivo], verbose_name='Área para Instalação (m²)'),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='conta_luz',
            field=models.FloatField(default=0, validators=[simulador.validators.validar_positivo], verbose_name='Valor da Conta de Luz (R$)'),
        ),
        migrations.AlterField(
            model_name='painelsolar',
            name='potencia',
            field=models.FloatField(validators=[simulador.validators.validar_positivo], verbose_name='Potência (W)'),
        ),
    ]
